##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: CrediYa
  devtools:
    add-properties: false
  profiles:
    include:
  sql:
    init:
      mode: always
      schema-locations: schema.sql
database:
  host: ${AUTH_SERVICE_DB_HOST}
  port: ${AUTH_SERVICE_DB_PORT}
  username: ${AUTH_SERVICE_DB_USERNAME}
  password: ${AUTH_SERVICE_DB_PASSWORD}
  name: ${AUTH_SERVICE_DB_NAME}

